// default package
// Generated Nov 20, 2017 4:23:37 PM by Hibernate Tools 5.2.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Peliculas generated by hbm2java
 */
public class Peliculas implements java.io.Serializable {

	private Integer codigo;
	private String titulo;
	private Date fecha;
	private double presupuesto;
	private Set repartos = new HashSet(0);

	public Peliculas() {
	}

	public Peliculas(String titulo, Date fecha, double presupuesto) {
		this.titulo = titulo;
		this.fecha = fecha;
		this.presupuesto = presupuesto;
	}

	public Peliculas(String titulo, Date fecha, double presupuesto, Set repartos) {
		this.titulo = titulo;
		this.fecha = fecha;
		this.presupuesto = presupuesto;
		this.repartos = repartos;
	}

	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public double getPresupuesto() {
		return this.presupuesto;
	}

	public void setPresupuesto(double presupuesto) {
		this.presupuesto = presupuesto;
	}

	public Set getRepartos() {
		return this.repartos;
	}

	public void setRepartos(Set repartos) {
		this.repartos = repartos;
	}

}
